services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nodejs_app
        ports:
            - "8080:8080"
        env_file:
            - .env
        environment:
            - NODE_ENV=production
        restart: unless-stopped
        volumes:
            - ./logs:/app/logs
            - node_modules:/app/node_modules
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    node_modules:
